insert into event_seed (
    id,
    organizer_id,
    group_id,
    category_id,
    slug,
    title,
    description,
    city,
    country,
    venue_name,
    start_date,
    end_date,
    is_online,
    is_hybrid,
    is_free,
    price,
    currency,
    status,
    reminders_enabled
) values
    (
        'event-july-1',
        'org-1',
        'group-1',
        'cat-dance',
        'sunset-ecstatic-dance-july',
        'Sunset Ecstatic Dance',
        'Sesión de danza consciente al atardecer con DJ set orgánico y cierre en silencio.',
        'Madrid',
        'España',
        'Espacio Matadero',
        '2026-07-11 19:00:00',
        '2026-07-11 22:00:00',
        false,
        false,
        false,
        24.00,
        'EUR',
        'PUBLISHED',
        true
    ),
    (
        'event-july-2',
        'org-2',
        'group-2',
        'cat-workshops',
        'urban-breathwork-july',
        'Urban Breathwork Lab',
        'Laboratorio guiado de respiración, regulación del sistema nervioso y journaling.',
        'Barcelona',
        'España',
        'Casa Virupa',
        '2026-07-18 10:00:00',
        '2026-07-18 13:30:00',
        false,
        false,
        false,
        32.00,
        'EUR',
        'PUBLISHED',
        true
    ),
    (
        'event-july-3',
        'org-2',
        null,
        'cat-music',
        'mantra-night-july',
        'Mantra Night Online',
        'Círculo digital de canto y meditación para comunidad hispanohablante.',
        'Online',
        '',
        'Karma Live Room',
        '2026-07-24 20:00:00',
        '2026-07-24 21:30:00',
        true,
        false,
        true,
        null,
        null,
        'PUBLISHED',
        true
    ),
    (
        'event-august-1',
        'org-1',
        'group-1',
        'cat-retreats',
        'summer-embodiment-retreat-august',
        'Summer Embodiment Retreat',
        'Fin de semana inmersivo con yoga suave, danza, cacao y baños de sonido.',
        'Sierra de Madrid',
        'España',
        'Finca El Bosque',
        '2026-08-07 17:00:00',
        '2026-08-09 16:00:00',
        false,
        false,
        false,
        185.00,
        'EUR',
        'PUBLISHED',
        true
    ),
    (
        'event-august-2',
        'org-2',
        'group-2',
        'cat-workshops',
        'park-yoga-sunrise-august',
        'Park Yoga Sunrise',
        'Clase abierta al amanecer con meditación breve y picnic comunitario.',
        'Barcelona',
        'España',
        'Parc de la Ciutadella',
        '2026-08-16 07:30:00',
        '2026-08-16 09:00:00',
        false,
        false,
        true,
        null,
        null,
        'PUBLISHED',
        true
    ),
    (
        'event-august-3',
        'org-1',
        null,
        'cat-music',
        'sound-healing-portal-august',
        'Sound Healing Portal',
        'Viaje inmersivo con cuencos, voz y ambient meditation.',
        'Valencia',
        'España',
        'Lumen Studio',
        '2026-08-28 19:30:00',
        '2026-08-28 21:30:00',
        false,
        false,
        false,
        28.00,
        'EUR',
        'PUBLISHED',
        true
    )
on conflict (id) do nothing;
